# Generated by Django 4.1.3 on 2022-12-20 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega1Daneri', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='camada',
            new_name='comision',
        ),
    ]
